### ISSUE TITLE
Integration of FETS Challenge findings into OpenFL

### ISSUE THREAD

**Issue by alexey-gruzdev** [eceisik/FeTS_Challenge_METU_FL_Team#1]
Hey @GorkemP @eceisik ! Very nice work in the scope of FETS Challenge. A lot of interesting ideas implemented. I wonder if you would like to contribute some major algorithms directly to [OpenFL repository](https://github.com/intel/openfl) in order for broader community to have opportunity to experiment with this out-of-the-box when they installed OpenFL. 

We could discuss details here our in [our Slack ](https://join.slack.com/t/openfl/shared_invite/zt-ovzbohvn-T5fApk05~YS_iZhjJ5yaTw) if you are interested. If no, please disregard the message and close the issue:)

**Comment by eceisik** [comment]
Hey @alexey-gruzdev,
We would love to do this and we look forward to hearing the details.
Best,
Ece
